### ISSUE TITLE
NEU-DAO 你懂的

### ISSUE THREAD

**Issue by li-haojia** [unbyte/we-are-fine#1]
求大佬破解

**Comment by unbyte** [comment]
现在每天有短信和微信提示并且只需要选两个选项就ok了，感觉自动填报的意义很少了。最近ddl比较多，后天可能更一下脚本

**Comment by unbyte** [comment]
are-u-ok 项目已更新 → https://github.com/unbyte/are-u-ok/commit/fd59bf3cd92b04990fef526c2951b5d240ab34e6

这个项目因为似乎用的人很少，我就暂时不做更新了，欢迎pr
